apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cert-manager
  name: cert-manager-cainjector-leases-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-cainjector-leases
subjects:
  - kind: ServiceAccount
    name: cert-manager-cainjector
    namespace: cert-manager
