apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-secrets-role
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "list", "watch", "delete"]
